services:
    php:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: weather_api_php
        volumes:
            - .:/var/www
        networks:
            - laravel

    nginx:
        image: nginx:alpine
        container_name: weather_api_nginx
        ports:
            - "8080:80"
        volumes:
            - .:/var/www
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php
        networks:
            - laravel

    mysql:
        image: mysql:8.0
        container_name: weather_api_mysql
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: weatherdb
            MYSQL_ROOT_PASSWORD: root
            MYSQL_USER: weather
            MYSQL_PASSWORD: weather
        ports:
            - "3306:3306"
        volumes:
            - mysql_data:/var/lib/mysql
        networks:
            - laravel

    scheduler:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: weather_scheduler
        volumes:
            - .:/var/www
        depends_on:
            - mysql
        networks:
            - laravel
        command: php artisan schedule:work

networks:
    laravel:
        driver: bridge

volumes:
    mysql_data:
